---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    expose: "true"
    app: spring-kafka-openshift-demo-consumer
    provider: fabric8
    version: 0.0.1-SNAPSHOT
    group: com.systemcraftsman.demo
  name: spring-kafka-openshift-demo-consumer
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: spring-kafka-openshift-demo-consumer
